### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by danieljosephbrennan** [fagbokforlaget/vue-jsonschema-form#2]
I like the react version, but would much rather have it working Vue.

**Comment by griter** [comment]
It's not like it's abandoned - I just had more important things to do. I'll try to contribute more to this project in coming weeks ;)

Any feedback is welcome!

**Comment by danieljosephbrennan** [comment]
Is it currently functional then? How can I set it up?

**Comment by griter** [comment]
Please treat this repo as a demo - I've just updated README file (check it for more information).

The main goal is to prepare NPM package to make the usage of this component easier.

**Comment by danieljosephbrennan** [comment]
Cool. I'm using the components locally with some success. Thanks for creating this.
